### ISSUE TITLE
Always show The authentication flow has completed.

### ISSUE THREAD

**Issue by ewiggin** [divinites/oauth-mail#1]
I create client_id, client_secret for Google Account.
Redirection url: http://localhost:10111/

Always show this message: "The authentication flow has completed." I can't do anything.

**Comment by divinites** [comment]
Hi, Thanks for your question. That sentence means literally: the authentication flow has complete so you can start using your email in sublime text. 

use command-shift -P open the command palette , type “oauth”, you will see several command that you can use.

**Comment by ewiggin** [comment]
When i choose "oauth" commands (send, write, etc.) always open a browser tab and show "The authentication flow has completed." and do nothing.

**Comment by divinites** [comment]
Since you start another post, I suppose that you solved this problem.

**Comment by ewiggin** [comment]
No, i can't solve this problem.

**Comment by divinites** [comment]
If the "write" command also leads to open a browser, that would be really strange, since the code for writing an email does not involve any authentication process... 

any output from the command prompt window?

**Comment by amoksito** [comment]
Hello. I have the same problem. The "write" command just open a new tab with a Yaml block at the top. But, if I try to send a mail, the "The authentication flow has completed." always appears, and the mail is never send.

The command prompt window put: KeyError: 'refresh_token'

**Comment by divinites** [comment]
Hello, thanks for your feedback. Could you please post the error message from the command prompt here?
Also, it would be helpful to post your OauthMail.sublime-settings (with your private information masked of course), mine is as follows and I do not have problem sending email:

{
    "Mailboxs": [

```
                {
                    "identity": “XXXXX@gmail.com",

                    "parameters": {

                                    "name": “XXXXX",
                                    "client_id": “405583906945-XXXXXX.apps.googleusercontent.com",
                                    "client_secret": "FXXXPXXXXXU3",
                                    "default": "yes"
                                  }
                },

                {
                    "identity": “XXXXX@live.XX",
                    "parameters": {

                                    "name": "TXXXX",
                                    "client_id": "000XXXXXXDA",
                                    "client_secret": "0YdkVbXXXXXXXFdaDc",
                                    "default": "no"
                                 }
                }

            ],
"List Period": 4
```

}

**Comment by divinites** [comment]
Welcome to test the new version!

**Comment by gongon0108** [comment]
Did you solve this? I suffer from the same problem. I really wonder how to solve it...

**Comment by NiceSugar** [comment]
> Did you solve this? I suffer from the same problem. I really wonder how to solve it...

Me too.Did you solve it?
