### ISSUE TITLE
can't send mail

### ISSUE THREAD

**Issue by charliesgames** [divinites/oauth-mail#3]
Hi,

I can view the mail list, but i get this error when trying to send something.

530, b'5.7.0 Must issue a STARTTLS command first. ft4sm24307082wjb.37 - gsmtp')
OauthMail >>> failed.

I noticed that it says "OauthMail >>> TLS flag is set to False", where exactly can i set this to true?
 I'm using gmail.

hopefully you can help, this plugin looks super handy!

Cheers
Charlie

**Comment by divinites** [comment]
There is a tls flag in setting files:

```
                {
                    "identity": “XXXX@gmail.com",
                    "authentication": "oauth",

                    "parameters": {

                                    "name": "",
                                    "client_id": "",
                                    "client_secret": "",
                                    "tls": "yes",
                                    "default": "yes"
                                  }
                },
```

adding  “tls”: “yes” in the parameter segment will run starttls. If you encounter other problems, please let me know.

best wishes 
.

**Comment by charliesgames** [comment]
Wow, that was quick!

Thanks a bunch :)

Cheers
Charlie
