### ISSUE TITLE
Redirect url doesn't match

### ISSUE THREAD

**Issue by Aya-Yang** [divinites/oauth-mail#5]
I use sublime text 3, and I followed the instruction to configure gmail, but when I used the command "send_mail", it turned out to be a 400 error, and showed "Redirect url doesn't match"

**Comment by divinites** [comment]
Hi, Thanks for your feedbacks.

Could you please tell me whether you are using a client_secret file or you explicitly fill in client_id and client_secret in the sublime_setting file?

If would also be helpful to paste the information displayed in the command console. The default Redirect_url is http://localhost:10111

**Comment by Aya-Yang** [comment]
![image](https://cloud.githubusercontent.com/assets/12084255/14587802/2ad7b696-04ec-11e6-8652-9b805b50123a.png)
![2016-04-17 10 00 31](https://cloud.githubusercontent.com/assets/12084255/14587811/3957f730-04ec-11e6-9270-713e6776aec1.png)
I added the default Redirect_url in my google app, and it worked, but when I used the command Send E-mail.it would always ask for authorization

**Comment by divinites** [comment]
That's weird, since when the authentication process is supposed to run once and store the value in the Packages/Users/QuickMail.cache, could you please check if you have this folder in $(your sublime text package folder)/Users?

**Comment by Aya-Yang** [comment]
I can't find that folder

**Comment by divinites** [comment]
Okay, thanks. I think I need to look at the code to find possible bugs. will get back to you soon!

**Comment by divinites** [comment]
sorry, I cannot replicate this bug based on the information that you provided,  issue closed at this moment, if you have any update, please do not hesitate to re-open this issue.
