### ISSUE TITLE
[Question] Zoho Mail support

### ISSUE THREAD

**Issue by Kristinita** [divinites/oauth-mail#8]
I use [Zoho Mail](https://www.zoho.com/mail/), my address, for example, is `example@kristinita.ru`. I'm sorry, you could add to README.MD, how to begin to use `oauth-mail`for Zoho Mail? If I can authorization use a token, but not use a password, it is very good.

Thanks.

**Comment by divinites** [comment]
Hi, Kristinita,  thanks for submitting issues.

I had a look at Zoho mail, although it does support oauth authentication, 

https://www.zoho.com/crm/help/api/using-authentication-token.html

it supports it  in a way which is more like what Github does (oauthtoken), but a bit far from the way of Microsoft hotmail and Google's gmail (client_id, client_secret). Therefore, there is no easy way to add zoho mail support to this plug-in I am afraid.
