### ISSUE TITLE
how to send email?

### ISSUE THREAD

**Issue by syntheticperson** [divinites/oauth-mail#9]
The documentation does not explain how to send an email with the command:
**send_as_mail**: this command will add email header on top of all the content in current view
I fill out my sublime text 3 window with the text ready to send.
I select send as email from the command palette, filling out the email address.
But what is the keyboard or menu command to actually send the email?
thanks

**Comment by divinites** [comment]
Hi, the command is Gmail: Send E-Mail. :-)

**Comment by syntheticperson** [comment]
Ah! So it's a 2 step process.
Populate window with text.
Select command send as email
Fill out the recipient details
Then select command send email
thanks!
